### ISSUE TITLE
Implement Classified Polygon Widget

### ISSUE THREAD

**Issue by timlinux** [kartoza/GEEST2#22]
We would require drop down and data box for this plug-in

![image](https://github.com/user-attachments/assets/a9bcc30a-6414-4ed6-89a6-ae4da82046a6)

See #18 for back-end functionality

**Comment by hennie-k** [comment]
- The example widget shown in the image allows input of "Point, Polygon or Raster", but the ticket only refers to polygon layers, which will be the only input type handled by this widget as per ticket description.
- The image also shows a combobox to select the Field Of Interest in the polygon layer, but there is no field in the input/output dict to hold this field value. The defining spreadsheet (from which the json model is generated) would either have to define this field so that it is included in the input/output dict, or there has to be a well-defined pattern/protocol specification for the format of the `Use Classify Poly into Classes` field in the output dict
