### ISSUE TITLE
Additional widget in Education

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/GEEST2#539]
There is an additional widget in Education which should not be there
![image](https://github.com/user-attachments/assets/3314e8cf-963f-4a08-b557-65cd41b7d155)

**Comment by timlinux** [comment]
@mvmaltitz this is because it is coded incorrectly in the spreadsheet

![image](https://github.com/user-attachments/assets/8c6bd644-97b3-4c1e-8b5b-e94e0e70a4a8)


I will fix it in the sheet and the data model, but you will need to start a new project after my fix is applied to see the update (or manually set your model.json value for this to 0).

**Comment by timlinux** [comment]
![image](https://github.com/user-attachments/assets/b6651d38-a1bd-4cca-bf7c-85eba1a61fdc)
